# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14MAYOA4VoMIFRy5rNog_ExGRK7r3EMhJ
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("paramaggarwal/fashion-product-images-dataset")

print("Path to dataset files:", path)

GROQ_API_KEY = "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"  # paste here

import pandas as pd
import numpy as np
import os
from google.colab import files

# Dataset
path = "/kaggle/input/fashion-product-images-dataset"
df = pd.read_csv(f"{path}/fashion-dataset/styles.csv", on_bad_lines='skip')

# Upload the .npy files you downloaded earlier
print("Upload embedding_vectors.npy")
files.upload()
print("Upload embedding_ids.npy")
files.upload()

vectors   = np.load('embedding_vectors.npy')
ids       = np.load('embedding_ids.npy')
id_to_idx = {int(pid): idx for idx, pid in enumerate(ids)}

print(f"✅ Dataset: {df.shape[0]} products")
print(f"✅ Embeddings: {vectors.shape}")

#pip install groq
from groq import Groq

client = Groq(api_key=GROQ_API_KEY)

def llm(messages: list, temperature: float = 0.7) -> str:
    """Single reusable LLM call using Groq + Llama3."""
    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=messages,
        temperature=temperature,
    )
    return response.choices[0].message.content.strip()

# Quick test
print(llm([{"role": "user", "content": "Say hello as a fashion stylist in one line."}]))

from collections import defaultdict
from sklearn.metrics.pairwise import cosine_similarity

preference_store = defaultdict(float)

LIKE_WEIGHT    =  0.3
DISLIKE_WEIGHT = -0.3

def give_feedback(product_id: int, feedback: str):
    if feedback == 'like':
        preference_store[product_id] += LIKE_WEIGHT
        _propagate_feedback(product_id, weight=0.1)
    elif feedback == 'dislike':
        preference_store[product_id] += DISLIKE_WEIGHT
        _propagate_feedback(product_id, weight=-0.1)

def _propagate_feedback(product_id: int, weight: float, top_k: int = 5):
    if product_id not in id_to_idx:
        return
    query_vec = vectors[id_to_idx[product_id]].reshape(1, -1)
    scores    = cosine_similarity(query_vec, vectors)[0]
    top_idx   = np.argsort(scores)[::-1][1:top_k+1]
    for idx in top_idx:
        preference_store[int(ids[idx])] += weight

def adjusted_score(product_id: int, clip_score: float) -> float:
    return clip_score + preference_store.get(product_id, 0.0)

print("✅ Preference store ready")

import json

def extract_intent(user_message: str) -> dict:
    system_prompt = """
You are a fashion intent parser. Extract structured info from the user's message.
Return ONLY a valid JSON object with these fields — no explanation, no markdown:
{
  "gender": "Men" | "Women" | "Unisex" | null,
  "usage": "Casual" | "Formal" | "Sports" | "Ethnic" | "Party" | null,
  "season": "Summer" | "Winter" | "Fall" | "Spring" | null,
  "occasion": string or null,
  "base_item": string or null,
  "refine": string or null
}

Examples:
User: "suggest a casual summer outfit for men"
→ {"gender":"Men","usage":"Casual","season":"Summer","occasion":null,"base_item":null,"refine":null}

User: "what goes with my navy blue shirt for a date night"
→ {"gender":null,"usage":"Casual","season":null,"occasion":"date night","base_item":"navy blue shirt","refine":null}

User: "make it more formal"
→ {"gender":null,"usage":"Formal","season":null,"occasion":null,"base_item":null,"refine":"more formal"}
"""
    raw = llm([
        {"role": "system", "content": system_prompt},
        {"role": "user",   "content": user_message}
    ], temperature=0)

    try:
        # Strip markdown if Llama wraps it
        clean = raw.replace("```json", "").replace("```", "").strip()
        return json.loads(clean)
    except:
        return {}

# Test
print(extract_intent("suggest a casual winter outfit for men"))

PAIRING_RULES = {
    "Topwear":    ["Bottomwear", "Shoes", "Sandal", "Watches", "Belts",
                   "Bags", "Eyewear", "Socks", "Ties", "Scarves", "Headwear"],
    "Bottomwear": ["Topwear", "Shoes", "Sandal", "Belts", "Socks",
                   "Watches", "Bags", "Eyewear"],
    "Dress":      ["Shoes", "Sandal", "Bags", "Jewellery", "Watches",
                   "Eyewear", "Scarves", "Headwear"],
    "Saree":      ["Shoes", "Sandal", "Bags", "Jewellery",
                   "Watches", "Eyewear"],
    "Shoes":      ["Topwear", "Bottomwear", "Socks", "Watches", "Bags"],
}

NEUTRAL_COLORS = {"Black", "White", "Grey", "Navy Blue", "Beige",
                  "Cream", "Off White", "Charcoal", "Khaki", "Brown", "Tan"}

def colors_match(c1, c2):
    if c1 in NEUTRAL_COLORS or c2 in NEUTRAL_COLORS:
        return True
    return c1 == c2

def suggest_outfit(intent: dict, base_product_id: int = None, top_n: int = 3) -> dict:
    gender = intent.get('gender')
    usage  = intent.get('usage')
    season = intent.get('season')

    # Find base item if not provided
    if base_product_id is None:
        pool = df.copy()
        if gender: pool = pool[pool['gender'].isin([gender, 'Unisex'])]
        if usage:  pool = pool[pool['usage'] == usage]
        if season: pool = pool[pool['season'] == season]
        pool = pool[pool['subCategory'].isin(PAIRING_RULES.keys())]
        if pool.empty:
            return {"error": "No matching base item found"}
        base_row = pool.sample(1).iloc[0]
        base_product_id = int(base_row['id'])
    else:
        rows = df[df['id'] == base_product_id]
        if rows.empty:
            return {"error": "Product not found"}
        base_row = rows.iloc[0]

    sub_cat = base_row['subCategory']
    color   = base_row['baseColour']
    gender  = gender or base_row['gender']
    usage   = usage  or base_row['usage']
    season  = season or base_row['season']

    outfit = {
        "base_item": {
            "id":       int(base_product_id),
            "name":     base_row['productDisplayName'],
            "color":    color,
            "category": sub_cat,
        },
        "suggestions": {}
    }

    for cat in PAIRING_RULES.get(sub_cat, []):
        pool = df[df['subCategory'] == cat].copy()
        pool = pool[pool['gender'].isin([gender, 'Unisex'])]
        if usage:  pool = pool[pool['usage'] == usage]
        if season: pool = pool[pool['season'].isin([season, 'All Season']) | pool['season'].isna()]
        pool = pool[pool['baseColour'].apply(lambda c: colors_match(str(color), str(c)))]
        pool = pool.drop_duplicates(subset='productDisplayName')

        if len(pool) < top_n:
            pool = df[df['subCategory'] == cat].copy()
            pool = pool[pool['gender'].isin([gender, 'Unisex'])]
            pool = pool[pool['baseColour'].apply(lambda c: colors_match(str(color), str(c)))]
            pool = pool.drop_duplicates(subset='productDisplayName')

        if pool.empty or base_product_id not in id_to_idx:
            continue

        query_vec   = vectors[id_to_idx[base_product_id]].reshape(1, -1)
        pool_ids    = [pid for pid in pool['id'].tolist() if pid in id_to_idx]
        if not pool_ids:
            continue

        pool_vecs   = vectors[[id_to_idx[pid] for pid in pool_ids]]
        clip_scores = cosine_similarity(query_vec, pool_vecs)[0]

        # RL — adjust scores by preference
        final_scores = np.array([
            adjusted_score(pid, score)
            for pid, score in zip(pool_ids, clip_scores)
        ])

        top_idx = np.argsort(final_scores)[::-1][:top_n]
        suggestions = []
        for i in top_idx:
            pid = pool_ids[i]
            row = df[df['id'] == pid].iloc[0]
            suggestions.append({
                "id":    int(pid),
                "name":  row['productDisplayName'],
                "color": row['baseColour'],
                "score": round(float(final_scores[i]), 4)
            })

        outfit["suggestions"][cat] = suggestions

    return outfit

print("✅ Suggestion engine ready")

conversation_history = []

def chat(user_message: str, base_product_id: int = None) -> str:
    global conversation_history

    # 1. Extract intent
    intent = extract_intent(user_message)
    print(f"🧠 Intent: {intent}")

    # 2. Get suggestions
    outfit = suggest_outfit(intent, base_product_id)
    if "error" in outfit:
        return f"Sorry — {outfit['error']}. Could you give me more details?"

    # 3. Build outfit summary for LLM
    summary = f"Base item: {outfit['base_item']['name']} ({outfit['base_item']['color']})\n"
    for cat, items in outfit["suggestions"].items():
        summary += f"\n{cat}:\n"
        for item in items:
            summary += f"  - {item['name']} ({item['color']})\n"

    # 4. LLM formats naturally
    system_prompt = """
You are a warm, confident AI fashion stylist named Zara.
Given the user's request and outfit suggestions, respond naturally like a personal stylist.
Be concise and specific — mention actual item names.
End every response with one short question asking if they want to adjust anything.
Never mention scores or technical details.
"""

    conversation_history.append({"role": "user", "content": user_message})

    messages = (
        [{"role": "system", "content": system_prompt}]
        + conversation_history
        + [{"role": "user", "content": f"Outfit suggestions to present:\n{summary}"}]
    )

    reply = llm(messages, temperature=0.7)
    conversation_history.append({"role": "assistant", "content": reply})

    chat.last_outfit = outfit
    return reply

chat.last_outfit = None
print("✅ Chatbot ready")

def feedback(product_id: int, signal: str):
    give_feedback(product_id, signal)
    pref = preference_store[product_id]
    print(f"✅ {signal.upper()} recorded for {product_id} → preference: {pref:+.2f}")

# ── Conversation 1 ──
print("👤 User: suggest a casual winter outfit for men")
reply = chat("suggest a casual winter outfit for men")
print(f"\n🤖 Zara: {reply}")

# ── Like the first bottomwear ──
if chat.last_outfit and "Bottomwear" in chat.last_outfit["suggestions"]:
    liked = chat.last_outfit["suggestions"]["Bottomwear"][0]
    print(f"\n👍 User liked: {liked['name']}")
    feedback(liked["id"], "like")

# ── Conversation 2 — refine ──
print("\n👤 User: make it more formal")
reply2 = chat("make it more formal")
print(f"\n🤖 Zara: {reply2}")

# ── Dislike a shoes suggestion ──
if chat.last_outfit and "Shoes" in chat.last_outfit["suggestions"]:
    disliked = chat.last_outfit["suggestions"]["Shoes"][0]
    print(f"\n👎 User disliked: {disliked['name']}")
    feedback(disliked["id"], "dislike")

# ── Conversation 3 — ask again, RL should influence results ──
print("\n👤 User: casual winter outfit for men again")
reply3 = chat("casual winter outfit for men again")
print(f"\n🤖 Zara: {reply3}")

# ── Show preference store state ──
print("\n📊 Preference store (non-zero scores):")
for pid, score in sorted(preference_store.items(), key=lambda x: -abs(x[1])):
    name = df[df['id'] == pid]['productDisplayName'].values
    name = name[0] if len(name) else "Unknown"
    print(f"   {score:+.2f}  {pid} — {name}")

