# -*- coding: utf-8 -*-
"""CLIP_embedding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/121JsvLQtKJJm7Up4oLNaxGsnVPy6TzCa
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("paramaggarwal/fashion-product-images-dataset")

print("Path to dataset files:", path)

import pandas as pd
import os

path = "/kaggle/input/fashion-product-images-dataset"

df = pd.read_csv(f"{path}/fashion-dataset/styles.csv", on_bad_lines='skip')

print(f"✅ Dataset loaded: {df.shape}")
print(df.head(2))

import os

path = "/kaggle/input/fashion-product-images-dataset" # Corrected path

# Find where images are stored
for root, dirs, files in os.walk(path):
    if any(f.endswith('.jpg') for f in files):
        print(f"Images found at: {root}")
        print(f"Sample files: {files[:5]}")
        IMAGE_DIR = root
        break

import torch
import open_clip
from PIL import Image
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"
model, _, preprocess = open_clip.create_model_and_transforms('ViT-B-32', pretrained='openai')
model = model.to(device)
model.eval()

print(f"✅ CLIP loaded on {device}")

def get_embedding(product_id: int) -> np.ndarray | None:
    img_path = f"{IMAGE_DIR}/{product_id}.jpg"
    if not os.path.exists(img_path):
        print(f"Image not found: {img_path}")
        return None
    try:
        image = preprocess(Image.open(img_path).convert("RGB")).unsqueeze(0).to(device)
        with torch.no_grad():
            embedding = model.encode_image(image)
            embedding = embedding / embedding.norm(dim=-1, keepdim=True)
        return embedding.cpu().numpy()[0]
    except Exception as e:
        print(f"[skip] {product_id}: {e}")
        return None

# Test
test_id = int(df.iloc[0]['id'])
emb = get_embedding(test_id)
if emb is not None:
    print(f"✅ Embedding shape: {emb.shape}")
    print(f"   First 5 values: {emb[:5]}")

import numpy as np
from tqdm import tqdm

# Find image directory
for root, dirs, files in os.walk(path):
    if any(f.endswith('.jpg') for f in files):
        IMAGE_DIR = root
        break

print(f"📁 Image dir: {IMAGE_DIR}")

# Only process IDs that have an image file
available_ids = [
    int(f.replace('.jpg', ''))
    for f in os.listdir(IMAGE_DIR)
    if f.endswith('.jpg')
]
print(f"✅ Images available: {len(available_ids)}")

# Filter df to only available images
df_available = df[df['id'].isin(available_ids)].reset_index(drop=True)
print(f"✅ Products with images: {len(df_available)}")

embeddings = {}
failed = []

for _, row in tqdm(df_available.iterrows(), total=len(df_available)):
    pid = int(row['id'])
    emb = get_embedding(pid)
    if emb is not None:
        embeddings[pid] = emb
    else:
        failed.append(pid)

print(f"\n✅ Embeddings generated: {len(embeddings)}")
print(f"❌ Failed: {len(failed)}")

import numpy as np

# Convert embeddings dictionary to numpy arrays
ids = np.array(list(embeddings.keys()))
vectors = np.array(list(embeddings.values()))

# Save the arrays to .npy files
np.save('embedding_vectors.npy', vectors)
np.save('embedding_ids.npy', ids)

# Now, load the saved arrays
vectors = np.load('embedding_vectors.npy')
ids = np.load('embedding_ids.npy')

print(f"✅ Vectors shape: {vectors.shape}")
print(f"✅ IDs shape: {ids.shape}")
print(f"   Sample ID: {ids[0]} → embedding: {vectors[0][:5]}")

from sklearn.metrics.pairwise import cosine_similarity

# Build a quick lookup: product_id → index in vectors array
id_to_idx = {pid: idx for idx, pid in enumerate(ids)}

def find_similar(product_id: int, subcategory: str, top_n: int = 5) -> list:
    """
    Find the most visually similar items within a specific subcategory.
    """
    if product_id not in id_to_idx:
        print(f"No embedding for {product_id}")
        return []

    # Get query embedding
    query_vec = vectors[id_to_idx[product_id]].reshape(1, -1)

    # Get all product IDs in the target subcategory
    cat_df = df[df['subCategory'] == subcategory]
    cat_ids = [pid for pid in cat_df['id'].tolist() if pid in id_to_idx]

    if not cat_ids:
        return []

    # Get their embeddings
    cat_indices = [id_to_idx[pid] for pid in cat_ids]
    cat_vectors = vectors[cat_indices]

    # Compute cosine similarity
    scores = cosine_similarity(query_vec, cat_vectors)[0]

    # Sort by score descending
    top_indices = np.argsort(scores)[::-1][:top_n]

    results = []
    for i in top_indices:
        pid = cat_ids[i]
        row = df[df['id'] == pid].iloc[0]
        results.append({
            "id": pid,
            "name": row['productDisplayName'],
            "color": row['baseColour'],
            "score": round(float(scores[i]), 4)
        })

    return results

# Test it
test_id = int(df[df['subCategory'] == 'Topwear'].iloc[0]['id'])
print(f"Finding Bottomwear matches for product {test_id}...\n")
matches = find_similar(test_id, 'Bottomwear', top_n=5)
for m in matches:
    print(f"  {m['score']:.4f} — {m['name']} ({m['color']})")

PAIRING_RULES = {
    "Topwear": ["Bottomwear", "Shoes", "Sandal", "Flip Flops", "Watches",
                "Belts", "Bags", "Jewellery", "Eyewear", "Socks", "Ties",
                "Scarves", "Mufflers", "Headwear"],
    "Bottomwear": ["Topwear", "Shoes", "Sandal", "Flip Flops", "Belts",
                   "Socks", "Watches", "Bags", "Eyewear"],
    "Dress": ["Shoes", "Sandal", "Flip Flops", "Bags", "Jewellery",
              "Watches", "Eyewear", "Scarves", "Headwear"],
    "Saree": ["Shoes", "Sandal", "Bags", "Jewellery", "Watches",
              "Eyewear", "Scarves"],
    "Shoes": ["Topwear", "Bottomwear", "Dress", "Socks", "Watches", "Bags", "Eyewear"],
    "Sandal": ["Topwear", "Bottomwear", "Dress", "Saree", "Bags", "Jewellery", "Watches"],
    "Flip Flops": ["Topwear", "Bottomwear", "Bags", "Watches", "Eyewear"],
    "Bags": ["Topwear", "Bottomwear", "Dress", "Shoes", "Sandal", "Watches", "Eyewear"],
    "Watches": ["Topwear", "Bottomwear", "Dress", "Shoes", "Bags"],
    "Jewellery": ["Topwear", "Dress", "Saree", "Bags", "Eyewear"],
    "Belts": ["Topwear", "Bottomwear", "Shoes"],
    "Socks": ["Topwear", "Bottomwear", "Shoes"],
    "Ties": ["Topwear", "Bottomwear", "Shoes", "Watches"],
    "Headwear": ["Topwear", "Bottomwear", "Shoes", "Eyewear"],
    "Scarves": ["Topwear", "Bottomwear", "Bags"],
    "Mufflers": ["Topwear", "Bottomwear", "Shoes"],
    "Eyewear": ["Topwear", "Bottomwear", "Dress", "Shoes", "Bags", "Watches"],
    "Wallets": ["Bags", "Watches", "Belts"],
    "Innerwear": ["Topwear", "Bottomwear", "Socks"],
    "Apparel Set": ["Shoes", "Sandal", "Bags", "Watches", "Eyewear"],
    "Loungewear and Nightwear": ["Flip Flops", "Socks", "Innerwear"],
}

NEUTRAL_COLORS = {"Black", "White", "Grey", "Navy Blue", "Beige", "Cream",
                  "Off White", "Charcoal", "Khaki", "Brown", "Tan"}

COLOR_HARMONY = {
    "Red":       ["Black", "White", "Navy Blue", "Grey", "Beige"],
    "Blue":      ["White", "Grey", "Black", "Beige", "Brown"],
    "Green":     ["White", "Black", "Beige", "Brown", "Khaki"],
    "Yellow":    ["White", "Black", "Grey", "Navy Blue"],
    "Pink":      ["White", "Black", "Grey", "Navy Blue", "Beige"],
    "Orange":    ["White", "Black", "Navy Blue", "Brown"],
    "Purple":    ["White", "Black", "Grey", "Beige"],
    "Maroon":    ["White", "Black", "Beige", "Khaki"],
    "Mustard":   ["White", "Black", "Brown", "Beige", "Navy Blue"],
    "Rust":      ["White", "Black", "Brown", "Beige", "Khaki"],
    "Turquoise": ["White", "Black", "Navy Blue", "Beige"],
    "Lavender":  ["White", "Grey", "Black", "Beige"],
}

def colors_match(color1: str, color2: str) -> bool:
    if color1 in NEUTRAL_COLORS or color2 in NEUTRAL_COLORS:
        return True
    if color1 == color2:
        return True
    return color2 in COLOR_HARMONY.get(color1, [])


def get_outfit_clip(product_id: int, top_n: int = 3) -> dict:
    """
    Rule engine + CLIP visual similarity combined.
    Rules decide WHICH categories to pair.
    CLIP decides WHICH specific items look best.
    """

    # ── 1. Find the item ──
    item_rows = df[df['id'] == product_id]
    if item_rows.empty:
        return {"error": f"Product {product_id} not found"}

    item = item_rows.iloc[0]
    sub_cat = item['subCategory']
    gender  = item['gender']
    season  = item['season']
    usage   = item['usage']
    color   = item['baseColour']

    print(f"\n👕 {item['productDisplayName']}")
    print(f"   {sub_cat} | {color} | {gender} | {season} | {usage}\n")

    compatible_cats = PAIRING_RULES.get(sub_cat, [])
    if not compatible_cats:
        return {"error": f"No rules for '{sub_cat}'"}

    outfit = {"selected_item": item.to_dict(), "suggestions": {}}

    for cat in compatible_cats:

        # ── 2. Rule-based pre-filter ──
        pool = df[df['subCategory'] == cat].copy()
        pool = pool[pool['gender'].isin([gender, 'Unisex'])]
        pool = pool[pool['season'].isin([season, 'All Season']) | pool['season'].isna()]
        pool = pool[pool['usage'] == usage]
        pool = pool[pool['baseColour'].apply(lambda c: colors_match(str(color), str(c)))]
        pool = pool.drop_duplicates(subset='productDisplayName')

        # Relax filters if pool too small
        if len(pool) < top_n:
            pool = df[df['subCategory'] == cat].copy()
            pool = pool[pool['gender'].isin([gender, 'Unisex'])]
            pool = pool[pool['baseColour'].apply(lambda c: colors_match(str(color), str(c)))]
            pool = pool.drop_duplicates(subset='productDisplayName')

        if pool.empty:
            continue

        # ── 3. CLIP similarity ranking ──
        if product_id not in id_to_idx:
            # fallback to rule-based only
            suggestions = pool.head(top_n)[
                ['id', 'productDisplayName', 'baseColour', 'usage']
            ].to_dict('records')
            outfit["suggestions"][cat] = suggestions
            continue

        query_vec = vectors[id_to_idx[product_id]].reshape(1, -1)
        pool_ids  = [pid for pid in pool['id'].tolist() if pid in id_to_idx]

        if not pool_ids:
            continue

        pool_vecs  = vectors[[id_to_idx[pid] for pid in pool_ids]]
        scores     = cosine_similarity(query_vec, pool_vecs)[0]
        top_idx    = np.argsort(scores)[::-1][:top_n]

        suggestions = []
        for i in top_idx:
            pid = pool_ids[i]
            row = df[df['id'] == pid].iloc[0]
            suggestions.append({
                "id":    pid,
                "name":  row['productDisplayName'],
                "color": row['baseColour'],
                "usage": row['usage'],
                "score": round(float(scores[i]), 4)
            })

        outfit["suggestions"][cat] = suggestions

    return outfit


# ── Pretty print ──
def display_outfit_clip(product_id: int):
    result = get_outfit_clip(product_id)
    if "error" in result:
        print(result["error"])
        return

    print("=" * 55)
    print("✨ AI STYLIST — CLIP POWERED OUTFIT")
    print("=" * 55)
    for cat, items in result["suggestions"].items():
        print(f"\n  {cat}:")
        for item in items:
            print(f"    • {item['name']} ({item['color']}) — score: {item['score']}")

# Test
display_outfit_clip(15970)

# Download the embeddings
from google.colab import files

files.download('embedding_vectors.npy')
files.download('embedding_ids.npy')

