# -*- coding: utf-8 -*-
"""outfit_pairer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pBJFi8gUzgMVye-2I9d_9684tc37F89m
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("paramaggarwal/fashion-product-images-dataset")

print("Path to dataset files:", path)

import pandas as pd

path = "/root/.cache/kagglehub/datasets/paramaggarwal/fashion-product-images-dataset/versions/1"

df = pd.read_csv(f"{path}/fashion-dataset/styles.csv", on_bad_lines='skip')
print(df.shape)
print(df.head())

print(df.shape)
print(df.columns.tolist())
print(df['subCategory'].value_counts())
print(df['articleType'].value_counts().head(20))

# ── Compatibility rules based on actual dataset subCategories ──

PAIRING_RULES = {
    "Topwear": ["Bottomwear", "Shoes", "Sandal", "Flip Flops", "Watches",
                "Belts", "Bags", "Jewellery", "Eyewear", "Socks", "Ties",
                "Scarves", "Mufflers", "Headwear"],

    "Bottomwear": ["Topwear", "Shoes", "Sandal", "Flip Flops", "Belts",
                   "Socks", "Watches", "Bags", "Eyewear"],

    "Dress": ["Shoes", "Sandal", "Flip Flops", "Bags", "Jewellery",
              "Watches", "Eyewear", "Scarves", "Headwear"],

    "Saree": ["Shoes", "Sandal", "Bags", "Jewellery", "Watches",
              "Eyewear", "Ties", "Scarves"],

    "Shoes": ["Topwear", "Bottomwear", "Dress", "Socks", "Watches",
              "Bags", "Eyewear"],

    "Sandal": ["Topwear", "Bottomwear", "Dress", "Saree", "Bags",
               "Jewellery", "Watches"],

    "Flip Flops": ["Topwear", "Bottomwear", "Bags", "Watches", "Eyewear"],

    "Bags": ["Topwear", "Bottomwear", "Dress", "Shoes", "Sandal",
             "Watches", "Eyewear"],

    "Watches": ["Topwear", "Bottomwear", "Dress", "Shoes", "Bags"],

    "Jewellery": ["Topwear", "Dress", "Saree", "Bags", "Eyewear"],

    "Innerwear": ["Topwear", "Bottomwear", "Socks"],

    "Eyewear": ["Topwear", "Bottomwear", "Dress", "Shoes", "Bags",
                "Watches", "Headwear"],

    "Belts": ["Topwear", "Bottomwear", "Shoes"],

    "Socks": ["Topwear", "Bottomwear", "Shoes"],

    "Ties": ["Topwear", "Bottomwear", "Shoes", "Watches", "Cufflinks"],

    "Cufflinks": ["Topwear", "Ties", "Watches"],

    "Headwear": ["Topwear", "Bottomwear", "Shoes", "Eyewear"],

    "Scarves": ["Topwear", "Bottomwear", "Bags"],

    "Mufflers": ["Topwear", "Bottomwear", "Shoes"],

    "Wallets": ["Bags", "Watches", "Belts"],

    "Loungewear and Nightwear": ["Flip Flops", "Socks", "Innerwear"],

    "Apparel Set": ["Shoes", "Sandal", "Bags", "Watches", "Eyewear"],
}

# ── Color harmony rules ──
# Neutrals go with everything. Bright colors need careful pairing.

NEUTRAL_COLORS = {"Black", "White", "Grey", "Navy Blue", "Beige", "Cream",
                  "Off White", "Charcoal", "Khaki", "Brown", "Tan"}

COLOR_HARMONY = {
    "Red":        ["Black", "White", "Navy Blue", "Grey", "Beige"],
    "Blue":       ["White", "Grey", "Black", "Beige", "Brown"],
    "Green":      ["White", "Black", "Beige", "Brown", "Khaki"],
    "Yellow":     ["White", "Black", "Grey", "Navy Blue"],
    "Pink":       ["White", "Black", "Grey", "Navy Blue", "Beige"],
    "Orange":     ["White", "Black", "Navy Blue", "Brown"],
    "Purple":     ["White", "Black", "Grey", "Beige"],
    "Maroon":     ["White", "Black", "Beige", "Khaki"],
    "Mustard":    ["White", "Black", "Brown", "Beige", "Navy Blue"],
    "Rust":       ["White", "Black", "Brown", "Beige", "Khaki"],
    "Turquoise":  ["White", "Black", "Navy Blue", "Beige"],
    "Lavender":   ["White", "Grey", "Black", "Beige"],
}

def colors_match(color1: str, color2: str) -> bool:
    """Return True if two colors are compatible."""
    if color1 in NEUTRAL_COLORS or color2 in NEUTRAL_COLORS:
        return True  # neutrals always work
    if color1 == color2:
        return True  # monochrome always works
    harmony = COLOR_HARMONY.get(color1, [])
    return color2 in harmony

print("✅ Pairing rules loaded.")
print(f"   {len(PAIRING_RULES)} categories covered")

def get_outfit(product_id: int, n: int = 3) -> dict:
    """
    Given a product ID, return compatible outfit suggestions.
    n = number of suggestions per category
    """

    # ── 1. Find the item ──
    item_rows = df[df['id'] == product_id]
    if item_rows.empty:
        return {"error": f"Product ID {product_id} not found"}

    item = item_rows.iloc[0]
    sub_cat   = item['subCategory']
    gender    = item['gender']
    season    = item['season']
    usage     = item['usage']
    color     = item['baseColour']

    print(f"\n👕 Selected: {item['productDisplayName']}")
    print(f"   Category: {sub_cat} | Color: {color} | Gender: {gender}")
    print(f"   Season: {season} | Usage: {usage}\n")

    # ── 2. Get compatible categories ──
    compatible_cats = PAIRING_RULES.get(sub_cat, [])
    if not compatible_cats:
        return {"error": f"No pairing rules found for '{sub_cat}'"}

    outfit = {"selected_item": item.to_dict(), "suggestions": {}}

    # ── 3. Filter & score for each compatible category ──
    for cat in compatible_cats:
        pool = df[df['subCategory'] == cat].copy()

        if pool.empty:
            continue

        # Layer 2a — gender filter
        pool = pool[pool['gender'].isin([gender, 'Unisex'])]

        # Layer 2b — season filter (allow NaN seasons)
        pool = pool[pool['season'].isin([season, 'All Season']) | pool['season'].isna()]

        # Layer 2c — usage filter
        pool = pool[pool['usage'] == usage]

        # Layer 2d — color harmony
        pool = pool[pool['baseColour'].apply(
            lambda c: colors_match(str(color), str(c))
        )]

        if pool.empty:
            # Relax usage filter if nothing found
            pool = df[df['subCategory'] == cat].copy()
            pool = pool[pool['gender'].isin([gender, 'Unisex'])]
            pool = pool[pool['baseColour'].apply(
                lambda c: colors_match(str(color), str(c))
            )]

        if pool.empty:
            continue

        # Pick top n
        # Replace pool.head(n) with this in your get_outfit function
        suggestions = pool.drop_duplicates(subset='productDisplayName').head(n)[
            ['id', 'productDisplayName', 'baseColour', 'usage', 'season']
        ].to_dict('records')
        outfit["suggestions"][cat] = suggestions

    return outfit


# ── Test it ──
result = get_outfit(1163)  # try any product ID from the dataset
if "error" in result:
    print(result["error"])
else:
    for category, items in result["suggestions"].items():
        print(f"📦 {category}:")
        for item in items:
            print(f"   - {item['productDisplayName']} ({item['baseColour']})")

def display_outfit(product_id: int):
    result = get_outfit(product_id)

    if "error" in result:
        print(result["error"])
        return

    print("=" * 50)
    print("✨ COMPLETE OUTFIT SUGGESTION")
    print("=" * 50)

    base = result["selected_item"]
    print(f"\n🧢 BASE ITEM")
    print(f"   {base['productDisplayName']}")
    print(f"   {base['subCategory']} | {base['baseColour']} | {base['usage']}\n")

    print("👗 PAIR WITH:\n")
    for category, items in result["suggestions"].items():
        print(f"  {category}:")
        for item in items:
            print(f"    • {item['productDisplayName']} — {item['baseColour']}")
        print()

display_outfit(1163)

# Test across different categories
test_ids = [
    df[df['subCategory'] == 'Topwear'].iloc[0]['id'],
    df[df['subCategory'] == 'Bottomwear'].iloc[0]['id'],
    df[df['subCategory'] == 'Dress'].iloc[0]['id'],
    df[df['subCategory'] == 'Saree'].iloc[0]['id'],
    df[df['subCategory'] == 'Shoes'].iloc[0]['id'],
]

for pid in test_ids:
    display_outfit(int(pid))
    print("\n" + "="*50 + "\n")

# Save the pairing engine as a standalone module
code = '''
import pandas as pd

# paste your PAIRING_RULES dict here
# paste your NEUTRAL_COLORS set here
# paste your COLOR_HARMONY dict here
# paste your colors_match function here
# paste your get_outfit function here
# paste your display_outfit function here
'''

with open('outfit_pairer.py', 'w') as f:
    f.write(code)

print("✅ Saved as outfit_pairer.py")

