# -*- coding: utf-8 -*-
"""YOLO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-rkQ27WFl8NB7sarAuvtvaYxxYZ9qbjo
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("paramaggarwal/fashion-product-images-dataset")

print("Path to dataset files:", path)

import pandas as pd
import numpy as np
from google.colab import files

path = "/kaggle/input/fashion-product-images-dataset"
df = pd.read_csv(f"{path}/fashion-dataset/styles.csv", on_bad_lines='skip')

print("Upload embedding_vectors.npy")
files.upload()
print("Upload embedding_ids.npy")
files.upload()

vectors   = np.load('embedding_vectors.npy')
ids       = np.load('embedding_ids.npy')
id_to_idx = {int(pid): idx for idx, pid in enumerate(ids)}

print(f"✅ Dataset: {df.shape[0]} products")
print(f"✅ Embeddings: {vectors.shape}")

#pip install ultralytics --upgrade -q

import torch
from ultralytics import YOLO

# Download directly from ultralytics github
!wget -q "https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt" -O yolov8n.pt

# Verify file size — should be around 6MB
import os
size = os.path.getsize('yolov8n.pt')
print(f"File size: {size / 1024 / 1024:.2f} MB")

if size < 1000:
    print("❌ File too small — download failed")
else:
    yolo_model = YOLO('yolov8n.pt')
    print("✅ YOLO loaded")

# Install open_clip_torch if not already installed
#!pip install open_clip_torch
import torch
import open_clip
from PIL import Image
import requests
from io import BytesIO

device = "cuda" if torch.cuda.is_available() else "cpu"

# ── CLIP ──
clip_model, _, preprocess = open_clip.create_model_and_transforms(
    'ViT-B-32', pretrained='openai'
)
clip_model = clip_model.to(device)
clip_model.eval()

print(f"✅ YOLO loaded")
print(f"✅ CLIP loaded on {device}")

# DeepFashion2 category ID → our dataset subCategory
DEEPFASHION_TO_SUBCATEGORY = {
    0:  "Topwear",      # short sleeve top
    1:  "Topwear",      # long sleeve top
    2:  "Topwear",      # short sleeve outwear
    3:  "Topwear",      # long sleeve outwear
    4:  "Dress",        # vest dress
    5:  "Dress",        # sling dress
    6:  "Dress",        # short sleeve dress
    7:  "Dress",        # long sleeve dress
    8:  "Bottomwear",   # shorts
    9:  "Bottomwear",   # trousers
    10: "Bottomwear",   # skirt
    11: "Shoes",        # shoes
    12: "Bags",         # bag
}

# Fallback for standard YOLO COCO labels
COCO_TO_SUBCATEGORY = {
    "tie":        "Ties",
    "backpack":   "Bags",
    "handbag":    "Bags",
    "suitcase":   "Bags",
    "umbrella":   "Accessories",
}

def map_yolo_label(label: str, class_id: int) -> str:
    """Map YOLO detection label to our dataset subCategory."""
    # Try DeepFashion2 mapping first
    if class_id in DEEPFASHION_TO_SUBCATEGORY:
        return DEEPFASHION_TO_SUBCATEGORY[class_id]
    # Fallback to COCO label mapping
    return COCO_TO_SUBCATEGORY.get(label.lower(), "Topwear")

print("✅ Label mapping ready")

from sklearn.metrics.pairwise import cosine_similarity
import cv2
import numpy as np

def detect_and_embed(image_input) -> list:
    """
    Takes an image (path, URL, or PIL Image).
    Returns list of detected items with their CLIP embeddings.
    """
    # Load image
    if isinstance(image_input, str) and image_input.startswith("http"):
        resp = requests.get(image_input)
        img_pil = Image.open(BytesIO(resp.content)).convert("RGB")
    elif isinstance(image_input, str):
        img_pil = Image.open(image_input).convert("RGB")
    else:
        img_pil = image_input.convert("RGB")

    img_array = np.array(img_pil)

    # YOLO detection
    results = yolo_model(img_pil, verbose=False)
    detections = []

    for result in results:
        boxes = result.boxes
        if boxes is None or len(boxes) == 0:
            # No detection — embed the full image as fallback
            print("⚠️ No items detected — using full image")
            embedding = _embed_image(img_pil)
            detections.append({
                "label":     "Unknown",
                "subcat":    "Topwear",
                "confidence": 0.0,
                "embedding": embedding,
                "crop":      img_pil,
            })
            continue

        for box in boxes:
            x1, y1, x2, y2 = map(int, box.xyxy[0].tolist())
            conf  = float(box.conf[0])
            cls   = int(box.cls[0])
            label = result.names[cls]

            if conf < 0.3:
                continue

            # Crop detected region
            crop = img_pil.crop((x1, y1, x2, y2))

            # Map to our subcategory
            subcat = map_yolo_label(label, cls)

            # CLIP embed the crop
            embedding = _embed_image(crop)

            detections.append({
                "label":      label,
                "subcat":     subcat,
                "confidence": round(conf, 3),
                "embedding":  embedding,
                "crop":       crop,
            })
            print(f"  Detected: {label} → {subcat} (conf: {conf:.2f})")

    return detections


def _embed_image(img_pil: Image.Image) -> np.ndarray:
    """Generate CLIP embedding for a PIL image."""
    tensor = preprocess(img_pil).unsqueeze(0).to(device)
    with torch.no_grad():
        emb = clip_model.encode_image(tensor)
        emb = emb / emb.norm(dim=-1, keepdim=True)
    return emb.cpu().numpy()[0]

print("✅ Detection pipeline ready")

def find_similar_in_dataset(
    embedding: np.ndarray,
    subcategory: str,
    gender: str = None,
    usage: str = None,
    top_n: int = 5
) -> list:
    """
    Given a CLIP embedding, find most similar items
    in our dataset within a specific subcategory.
    """
    pool = df[df['subCategory'] == subcategory].copy()

    if gender:
        pool = pool[pool['gender'].isin([gender, 'Unisex'])]
    if usage:
        pool = pool[pool['usage'] == usage]

    pool = pool.drop_duplicates(subset='productDisplayName')

    pool_ids = [pid for pid in pool['id'].tolist() if pid in id_to_idx]
    if not pool_ids:
        return []

    pool_vecs = vectors[[id_to_idx[pid] for pid in pool_ids]]
    scores    = cosine_similarity(embedding.reshape(1, -1), pool_vecs)[0]
    top_idx   = np.argsort(scores)[::-1][:top_n]

    results = []
    for i in top_idx:
        pid = pool_ids[i]
        row = df[df['id'] == pid].iloc[0]
        results.append({
            "id":    int(pid),
            "name":  row['productDisplayName'],
            "color": row['baseColour'],
            "subcat": row['subCategory'],
            "score": round(float(scores[i]), 4),
        })

    return results

print("✅ Similarity search ready")

PAIRING_RULES = {
    "Topwear":    ["Bottomwear", "Shoes", "Sandal", "Watches", "Belts",
                   "Bags", "Eyewear", "Socks", "Ties", "Scarves"],
    "Bottomwear": ["Topwear", "Shoes", "Sandal", "Belts", "Socks",
                   "Watches", "Bags", "Eyewear"],
    "Dress":      ["Shoes", "Sandal", "Bags", "Jewellery",
                   "Watches", "Eyewear", "Scarves"],
    "Shoes":      ["Topwear", "Bottomwear", "Socks", "Watches", "Bags"],
    "Bags":       ["Topwear", "Bottomwear", "Shoes", "Watches", "Eyewear"],
}

def recommend_from_image(image_input, gender: str = None, usage: str = None) -> dict:
    """
    Full pipeline:
    Image → YOLO detect → CLIP embed → find match → pair outfit
    """
    print("\n🔍 Detecting clothing items...")
    detections = detect_and_embed(image_input)

    if not detections:
        return {"error": "No clothing detected in image"}

    # Use highest confidence detection as base
    base = max(detections, key=lambda x: x['confidence'])
    print(f"\n👕 Base item detected: {base['label']} → {base['subcat']}")

    # Find most similar item in our dataset
    print("\n🔎 Finding closest match in dataset...")
    matches = find_similar_in_dataset(
        base['embedding'],
        subcategory=base['subcat'],
        gender=gender,
        usage=usage,
        top_n=1
    )

    if not matches:
        return {"error": f"No matches found for {base['subcat']}"}

    matched_item = matches[0]
    matched_id   = matched_item['id']
    print(f"✅ Matched: {matched_item['name']} (score: {matched_item['score']})")

    # Now run pairing engine on matched item
    print("\n👗 Building outfit recommendations...")
    outfit = {"detected": base['label'],
              "matched_item": matched_item,
              "suggestions": {}}

    for cat in PAIRING_RULES.get(base['subcat'], []):
        similar = find_similar_in_dataset(
            vectors[id_to_idx[matched_id]],
            subcategory=cat,
            gender=gender,
            usage=usage,
            top_n=3
        )
        if similar:
            outfit["suggestions"][cat] = similar

    return outfit


def display_recommendation(result: dict):
    if "error" in result:
        print(f"❌ {result['error']}")
        return

    print("\n" + "="*55)
    print("✨ AI STYLIST — IMAGE BASED RECOMMENDATION")
    print("="*55)
    print(f"\n📸 Detected: {result['detected']}")
    print(f"🎯 Matched:  {result['matched_item']['name']} ({result['matched_item']['color']})")
    print(f"   Similarity score: {result['matched_item']['score']}")
    print("\n👗 Complete outfit:\n")
    for cat, items in result["suggestions"].items():
        print(f"  {cat}:")
        for item in items:
            print(f"    • {item['name']} ({item['color']}) — {item['score']}")

print("✅ Full pipeline ready")

# Test with a public fashion image URL
test_url = "https://images.unsplash.com/photo-1603252109303-2751441dd157?w=500"

result = recommend_from_image(test_url, gender="Men", usage="Casual")
display_recommendation(result)

# Upload any clothing photo from your phone or computer
uploaded = files.upload()
filename = list(uploaded.keys())[0]

result = recommend_from_image(filename, gender="Women", usage="Casual")
display_recommendation(result)

